volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  bitrixdock:

services:
  php:
    build: ./php82
    container_name: php
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
    restart: unless-stopped
  web_server:
    build: ./nginx
    container_name: web_server
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    networks:
      - bitrixdock
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  db:
    build: ./mysql
    container_name: db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    volumes_from:
      - source
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Moscow
    command: mysqld --user=root --sql-mode=""
    networks:
      - bitrixdock
    stdin_open: true
    tty: true
    restart: unless-stopped
  memcached:
    image: memcached:latest
    container_name: memcached
    volumes_from:
      - source
    ports:
      - '11211:11211'
    networks:
      - bitrixdock
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  adminer:
    image: dockette/adminer:full
    container_name: adminer
    links:
      - db:db
    ports:
      - '8080:80'
    environment:
      UPLOAD: 1024M # upload_max_filesize, post_max_size
      TZ: Europe/Moscow
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
  source:
    image: alpine:latest
    container_name: source
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php
      - ./logs/db:/var/log/mysql
      - ./logs/memcached:/var/log/memcached
      - db:/var/lib/mysql
      - cache:/var/lib/memcached
      - ${SITE_PATH}:/var/www/bitrix
      - /etc/localtime:/etc/localtime/:ro
    networks:
      - bitrixdock
